### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by EzazAA** [EzazAA/Swift-note#1]
### A better README.md (Documentation) is needed
Our requirements is as following -

* Correct English grammar
* GIFs and Emojis preferred
* Includes the following points
 - About
 - Code
 - Installation
 - Usage
 - Screenshot
 - Contribution

---
Thankyou 🎊

**Comment by uzefaqureshi06** [comment]
@EzazAA  can you give me this issue I want to work on it

**Comment by EzazAA** [comment]
@uzefaqureshi06 I have assigned you. If you need any advice please mention. And try to make it more engaging. Best of luck 👍
